
/*
 * GEM ionization model
 *
 * Overview:
 * IonModel simulates the primary ionization produced by one particle
 * crossing a GEM gas volume. It also models the transverse diffusion
 * during ion drift and the fluctuation of the GEM avalanche gain.
 * Each call processes one particle crossing one GEM gas volume.
 *
 * Model flow:
 * 1. Receive the particle entry point, exit point, and deposited energy.
 * 2. Swap in and out when out.Z() is smaller than in.Z(), so the track
 *    is always processed in the positive Z direction. The input vectors
 *    may therefore be modified.
 * 3. Calculate the mean number of primary ions from Edep / GasIonE and
 *    apply a Poisson fluctuation.
 * 4. Generate each ion position uniformly along the particle track.
 * 5. Calculate the drift time and transverse diffusion width from the
 *    distance to the readout plane, GasDriftVelocity, and GasDiffusion.
 * 6. Apply Gaussian fluctuations to the transverse position and GEM
 *    avalanche gain.
 * 7. Store every ion in the global fRIon vector and update Num_ions and
 *    the minimum drift time minTravelT.
 *
 * Input:
 *     TVector3& in        Particle entry position in the gas, in mm
 *     TVector3& out       Particle exit position from the gas, in mm
 *     const Double_t Edep Deposited energy in the gas, in MeV
 *
 * Output:
 *     fRIon       All ions generated by the current particle
 *     Num_ions    Number of generated ions
 *     minTravelT  Minimum drift time among the generated ions, in ns
 *
 * Each IonPar_t in fRIon contains:
 *     Xp, Yp      Ion position on the readout plane, in mm
 *     Charge      Charge after avalanche multiplication
 *     S_sigma     Transverse diffusion width
 *     Ttime       Ion drift time, in ns
 *     ggnorm      Normalization factor for the charge distribution model
 *     eff_sigma   Square of S_sigma
 *
 * Usage:
 *     TVector3 in(xIn, yIn, zIn);
 *     TVector3 out(xOut, yOut, zOut);
 *     IonModel(in, out, energyDeposit);
 *
 *     for (const IonPar_t& ion : fRIon) {
 *         Double_t x = ion.Xp;
 *         Double_t y = ion.Yp;
 *         Double_t charge = ion.Charge;
 *     }
 *
 * Note:
 * IonModel calls fRIon.clear() at the beginning of every invocation.
 * Therefore, fRIon contains only the ionization result of the most
 * recently processed particle. Use the result before the next call.
 */

#ifndef GEM_ION_MODEL_H
#define GEM_ION_MODEL_H

#include <cmath>

#include "TMath.h"
#include "TRandom.h"
#include "TVector3.h"

#include "GEMdigVariables.h"

inline void IonModel(TVector3& in, TVector3& out, const Double_t Edep) {
    //all the unit for position is mm
    fRIon.clear();
    if(out.Z() < in.Z()) {
        TVector3 buffer(in);
        in = out;
        out = buffer;
    }
    TVector3 dir = out - in;
    TVector3 track(dir);
    dir.SetMag(1.); // Normalize the direction vector
    //beam particle's position on the readout plane
    TVector3 readoutPos(out);
    readoutPos = readoutPos + dir * Zreadout;

    int Num_ions = 0;

    //number of primary ions
    if(Edep*1.e+6 > GasIonE){
        Num_ions = Edep*1.e+6 / GasIonE;
        Num_ions = gRandom->Poisson(Num_ions);
    }
    if(Num_ions > 10000) Num_ions = 10000;

    minTravelT = 1000000.;
    
    for(int j = 0; j < Num_ions; j++) {
        // Generate a random start position along the direction vector
        Double_t fraction = gRandom->Uniform(0., 1.0); // Random fraction along the direction vector
        TVector3 ionPos = in + fraction * track;

        //Get the traveling time of the ion
        Double_t Length = Zreadout + out.Z() - ionPos.Z();
        Double_t Time = Length / GasDriftVelocity; // in us

        // spatial sigma on readout [mm] after avalanche
        Double_t Spatial_sigma = sqrt(2. * GasDiffusion * Time);

        //Add the lateral uncertainty(get to the readout plane)
        ionPos.SetX(ionPos.X() + gRandom->Gaus(0., GasLateralUncertainty));
        ionPos.SetY(ionPos.Y() + gRandom->Gaus(0., GasLateralUncertainty));

        //Get total charge of one primary ion pair after avalanche
        //Double_t Charge = gRandom->Exp(gain_mean); // exponential distribution of the charge
        Double_t Gain0 = 40.;
        Double_t Charge = gRandom->Gaus(gain_mean, gain_mean/sqrt(Gain0)); // Gaussian distribution of the charge
        if(Charge < 0.) Charge = 0.;
        IonPar_t ip;
        ip.Xp = ionPos.X();
        ip.Yp = ionPos.Y();
        ip.Charge = Charge;
        ip.S_sigma = Spatial_sigma;
        ip.eff_sigma = Spatial_sigma * Spatial_sigma;
        ip.Ttime = Time * 1.e+3; // convert to ns
        minTravelT = TMath::Min(minTravelT, ip.Ttime);
        ip.ggnorm = ip.Charge * TMath::InvPi() / pow(Spatial_sigma*fSNormNsigma, 2.);

        ip.R2 = Spatial_sigma * Spatial_sigma * fSNormNsigma * fSNormNsigma;

        fRIon.push_back(ip);
        //cout << "X: " << ionPos.X() << " Y: " << ionPos.Y() << " Charge: " << Charge << " time: " << ip.Ttime << " Spatial sigma: " << ip.S_sigma << endl;
    }
}

#endif
